public enum EventID
{
    NONE,
    PLAYER_DEAD = 1,
    PLAYER_RESPAWN = 2,
    DISABLE_OUTLINE_BIRD = 3,
    BUY_PRODUCT_SUCCESS_FIRST = 4,
    BUY_PRODUCT_SUCCESS = 5,
    CHANGE_LANGUAGE = 6,
    REMOVE_ADS = 7,
    FLY_OUT_RANDOM = 8,
    NATIVE_ADS_LOAD_DONE = 9,
    BUY_SKILL_DONE = 10,
    SHOW_MARK = 11,
    ON_ADS = 12,
    OFF_ADS = 13,
    ON_ADS_CANVAS = 14,
    OFF_ADS_CANVAS = 15,
}